#ifndef PROJECT_GAME_GAME_STATE_H
#define PROJECT_GAME_GAME_STATE_H

typedef enum {
  GAME_STATE_MENU = 0,
  GAME_STATE_PLAYING,
  GAME_STATE_PAUSED,
  GAME_STATE_GAME_OVER,
  GAME_STATE_EXIT
} GameState;

#endif
